/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import static UI.FormulaDisplayPanel.ta_formula;

/**
 *
 * @author Elliot-VS
 */
public class FontDialog extends javax.swing.JDialog {

    private static class GetFontDialog{
        private static final FontDialog FONT_DIALOG = new FontDialog();
    }
    
    public static FontDialog getInstance(){
        return GetFontDialog.FONT_DIALOG;
    }
    
    private String fontName;
    private String fontStyle;
    private String fontSize;
    private int fontSty;
    private int fontSiz;

    private FontDialog() {

        initComponents();
        setTitle("FontDialog");
        setAlwaysOnTop(true);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fontNames = ge.getAvailableFontFamilyNames();
        fontNameBox.setModel(new DefaultComboBoxModel<String>(fontNames));

        String[] fontStyles = {"Plain", "Italic", "Bold", "Bold Italic"};
        fontStyleBox.setModel(new DefaultComboBoxModel<String>(fontStyles));

        String[] fontSizes = {"8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72"};
        fontSizeBox.setModel(new DefaultComboBoxModel(fontSizes));

        fontSizeBox.setSelectedIndex(5);
        fontStyle = (String) fontStyleBox.getSelectedItem();
        fontSize = (String) fontSizeBox.getSelectedItem();
        fontSty = getFontStyleByCnName(fontStyle);
        fontSiz = Integer.parseInt(fontSize);

        fontNameBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                fontName = (String) e.getItem();
                Font font = new Font(fontName, fontSty, fontSiz);
                previewTa.setFont(font);
            }
        });

        fontSizeBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                fontSize = (String) e.getItem();
                fontSiz = Integer.parseInt(fontSize);

                Font font = new Font(fontName, fontSty, fontSiz);
                previewTa.setFont(font);

            }
        });

        fontStyleBox.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent itemevent) {
                fontStyle = (String) itemevent.getItem();
                fontSty = getFontStyleByCnName(fontStyle);

                Font f = new Font(fontName, fontSty, fontSiz);
                previewTa.setFont(f);
            }
        });
    }

    public int getFontStyleByCnName(String fontStyle) {
        if (fontStyle.equals("Plain")) {
            return Font.PLAIN;
        }
        if (fontStyle.equals("Italic")) {
            return Font.ITALIC;
        }
        if (fontStyle.equals("Bold")) {
            return Font.BOLD;
        }
        if (fontStyle.equals("Bold Italic")) {
            return (Font.BOLD + Font.ITALIC);
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fontNameBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        fontSizeBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fontStyleBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ConfirmBt = new javax.swing.JButton();
        CancelBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        previewTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 280));
        setName("FontDialog"); // NOI18N
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Font");

        fontNameBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Font Size");

        fontSizeBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Font Style");

        fontStyleBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Preview:");

        ConfirmBt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmBt.setText("Confirm");
        ConfirmBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtActionPerformed(evt);
            }
        });

        CancelBt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CancelBt.setText("Cancel");
        CancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtActionPerformed(evt);
            }
        });

        previewTa.setEditable(false);
        previewTa.setColumns(20);
        previewTa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        previewTa.setLineWrap(true);
        previewTa.setRows(5);
        previewTa.setText("I hava a cat that sat on a mat that was red that was my favorite.");
        jScrollPane1.setViewportView(previewTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fontNameBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fontStyleBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fontSizeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(ConfirmBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelBt, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fontSizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fontStyleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelBtActionPerformed

    private void ConfirmBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtActionPerformed
        // TODO add your handling code here:
        Font f = new Font(fontName, fontSty, fontSiz);
        ta_formula.setFont(f);
        
        this.dispose();
    }//GEN-LAST:event_ConfirmBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBt;
    private javax.swing.JButton ConfirmBt;
    private javax.swing.JComboBox<String> fontNameBox;
    private javax.swing.JComboBox<String> fontSizeBox;
    private javax.swing.JComboBox<String> fontStyleBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea previewTa;
    // End of variables declaration//GEN-END:variables
}
