/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.MouseEvent;
import static UI.FunctionPanel.bt_generate;
import Util.ClipBoard;
import Util.GenerateSVG;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Elliot-VS
 */
public class FormulaDisplayPanel extends javax.swing.JPanel {

    private FunctionPanel fp;

    /**
     * Creates new form FormulaDisplayPanel
     */
    public FormulaDisplayPanel() {
        initComponents();
        ta_formula.setCaretColor(Color.RED);
        ta_formula.setSelectionColor(Color.MAGENTA);
        fp = new FunctionPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm_formula = new javax.swing.JPopupMenu();
        mt_paste = new javax.swing.JMenuItem();
        mt_Cut = new javax.swing.JMenuItem();
        mt_Clear = new javax.swing.JMenuItem();
        mt_Generate = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_formula = new javax.swing.JTextArea();

        mt_paste.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mt_paste.setForeground(java.awt.Color.magenta);
        mt_paste.setText("Paste");
        mt_paste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mt_pasteMousePressed(evt);
            }
        });
        pm_formula.add(mt_paste);

        mt_Cut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mt_Cut.setForeground(java.awt.Color.magenta);
        mt_Cut.setText("Cut");
        mt_Cut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mt_CutMousePressed(evt);
            }
        });
        pm_formula.add(mt_Cut);

        mt_Clear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mt_Clear.setForeground(java.awt.Color.magenta);
        mt_Clear.setText("Clear");
        mt_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mt_ClearMousePressed(evt);
            }
        });
        mt_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mt_ClearActionPerformed(evt);
            }
        });
        pm_formula.add(mt_Clear);

        mt_Generate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mt_Generate.setForeground(java.awt.Color.magenta);
        mt_Generate.setText("Clip This Formula");
        mt_Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mt_GenerateActionPerformed(evt);
            }
        });
        pm_formula.add(mt_Generate);

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ta_formula.setColumns(20);
        ta_formula.setFont(new java.awt.Font("KaiTi", 0, 24)); // NOI18N
        ta_formula.setLineWrap(true);
        ta_formula.setRows(5);
        ta_formula.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ta_formulaCaretUpdate(evt);
            }
        });
        ta_formula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ta_formulaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(ta_formula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ta_formulaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ta_formulaCaretUpdate
        // TODO add your handling code here:
        if ("".equals(ta_formula.getText())) {
            bt_generate.setEnabled(false);
        } else {
            bt_generate.setEnabled(true);
        }

    }//GEN-LAST:event_ta_formulaCaretUpdate

    private void ta_formulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_formulaMousePressed
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            pm_formula.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ta_formulaMousePressed

    private void mt_pasteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mt_pasteMousePressed
        ta_formula.paste();
    }//GEN-LAST:event_mt_pasteMousePressed

    private void mt_CutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mt_CutMousePressed
        ta_formula.cut();
    }//GEN-LAST:event_mt_CutMousePressed

    private void mt_ClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mt_ClearMousePressed
        ta_formula.setText("");

    }//GEN-LAST:event_mt_ClearMousePressed

    private void mt_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mt_ClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mt_ClearActionPerformed

    private void mt_GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mt_GenerateActionPerformed
        try {

            String latex = ta_formula.getText().trim();
            String fileName = ".cache" + File.separator + ".temp" + ".svg";

            GenerateSVG.saveSVG(latex, fileName, 40);
            ClipBoard.copyToClipboard(fileName);

        } catch (IOException ex) {
            Logger.getLogger(FormulaDisplayPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_mt_GenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mt_Clear;
    private javax.swing.JMenuItem mt_Cut;
    private javax.swing.JMenuItem mt_Generate;
    private javax.swing.JMenuItem mt_paste;
    private javax.swing.JPopupMenu pm_formula;
    public static javax.swing.JTextArea ta_formula;
    // End of variables declaration//GEN-END:variables
}
