/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Elliot-VS
 */
public class IntroductionPanel extends javax.swing.JPanel {

    /**
     * Creates new form IntroductionPanel
     */
    public IntroductionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pm_introduction = new javax.swing.JPopupMenu();
        mt_copy = new javax.swing.JMenuItem();
        mt_goto = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_introduction = new javax.swing.JTextArea();

        mt_copy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mt_copy.setForeground(java.awt.Color.magenta);
        mt_copy.setText("Copy");
        mt_copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mt_copyMousePressed(evt);
            }
        });
        pm_introduction.add(mt_copy);

        mt_goto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mt_goto.setForeground(java.awt.Color.magenta);
        mt_goto.setText("Go to");
        mt_goto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mt_gotoMousePressed(evt);
            }
        });
        pm_introduction.add(mt_goto);

        setToolTipText("");

        jScrollPane2.setFont(new java.awt.Font("KaiTi", 0, 18)); // NOI18N

        ta_introduction.setEditable(false);
        ta_introduction.setBackground(java.awt.Color.lightGray);
        ta_introduction.setColumns(20);
        ta_introduction.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        ta_introduction.setLineWrap(true);
        ta_introduction.setRows(5);
        ta_introduction.setText("This software obeying the GPL-V3 license ( http://www.gnu.org/licenses/gpl.html ) is based on Java Swing and the open source library JLatexMath. Everyone is permitted to download the source code freely on GitHub website under the GPL-V3 license. Here are some information about this project.\n0. This version is CROSS-PLATFORM, which means it can run on any os that supports Java.                                       Compile Time: 20181115\n1. It's better for you to learn some Latex grammer, so that you can handle this software easily. FYI: https://en.wikipedia.org/wiki/LaTeX\n3. Please refer to the ReadMe.exe to get more information.\n4. E-mail: lsldragon@outlook.com ; 1178362914@qq.com\n5. Thanks to :\n                     [/facepalm]Me[/facepalm]\n                     the drag and drop function code refers to the source code of certchecker.jar\n                     the icon of this program     https://github.com/alecive/FlatWoken\n                     smart guys on GitHub\n\n");
        ta_introduction.setCaretPosition(0);
        ta_introduction.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ta_introduction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_introductionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ta_introduction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ta_introductionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_introductionMouseClicked
        // TODO add your handling code here:

        if (evt.getButton() == MouseEvent.BUTTON3) {
            pm_introduction.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ta_introductionMouseClicked

    private void mt_copyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mt_copyMousePressed
        // TODO add your handling code here:
        ta_introduction.copy();
    }//GEN-LAST:event_mt_copyMousePressed

    private void mt_gotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mt_gotoMousePressed
        try {

            String uri = ta_introduction.getSelectedText().trim();
            if (uri.startsWith("http") || uri.startsWith("https")) {
                Desktop.getDesktop().browse(new URI(uri));
            } else {
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), "Error: " + e.getMessage(), "FATAL ERROR", JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(IntroductionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mt_gotoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mt_copy;
    private javax.swing.JMenuItem mt_goto;
    private javax.swing.JPopupMenu pm_introduction;
    private javax.swing.JTextArea ta_introduction;
    // End of variables declaration//GEN-END:variables
}
