/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import SubWindows.DisplaySVG;
import Util.ConstantsUI;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static UI.FormulaDisplayPanel.ta_formula;
import static UI.FunctionPanel.bt_generate;
import Util.FileUtil;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Elliot-VS
 */
public class MainWindow extends javax.swing.JFrame implements DropTargetListener {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() throws IOException {

        setMainFrame();
        initComponents();
        CreatDirs();

        this.setIconImage(ConstantsUI.MAIN_WINDOW_ICON);

        DropTarget dt = new DropTarget(this, this);
        setDropTarget(dt);
        bt_generate.setEnabled(false);
    }

    /*
    Creat Formulas and Settings directories and debuglog.info, config.properties files
     */
    private void CreatDirs() throws IOException {

        File extendFormula = new File("extendFormula");
        if (!extendFormula.exists()) {
            extendFormula.mkdir();
        }

        File cache = new File(".cache");
        if (!cache.exists()) {
            cache.mkdir();
        }

        File settingsDir = new File(ConstantsUI.USER_HOME + File.separator + ".JFormula");
        if (!settingsDir.exists()) {
            settingsDir.mkdir();
        }

        File debugFile = new File(ConstantsUI.USER_HOME + File.separator + ".JFormula" + File.separator + ".Info.info");
        if (!debugFile.exists()) {
            debugFile.createNewFile();

            BufferedWriter bw = new BufferedWriter(new FileWriter(ConstantsUI.USER_HOME + File.separator + ".JFormula" + File.separator + ".Info.info"));
            String[] key = {"os.name", "os.arch", "os.version", "user.name", "file.encoding", "user.language", "user.home",
                "user.dir", "java.home"};
            for (int i = 0; i < key.length; i++) {
                String string = System.getProperty(key[i]);
                bw.write(key[i] + "=" + string);
                bw.newLine();
            }
            bw.write("Screen Size=" + setLocationCenter());
            bw.flush();
            bw.close();
        }
    }

    /*
    make the wondow in the center   haven't call this method
     */
    private String setLocationCenter() {

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dm = tk.getScreenSize();
        this.setLocation((int) (dm.getWidth() / 2) - (this.getWidth() / 2), (int) (dm.getHeight() / 2) - (this.getHeight() / 2));
        return dm.getWidth() + "*" + dm.getHeight();
    }

    private void setMainFrame() {

        Dimension resolution = Toolkit.getDefaultToolkit().getScreenSize();
        int showWidth = (int) (resolution.getWidth() * 0.8);
        int showHeight = (int) (resolution.getHeight() * 0.8);
        getContentPane().setPreferredSize(new Dimension(showWidth, showHeight));
        pack();
        int x = (int) ((resolution.getWidth() - getWidth()) / 2);
        int y = (int) ((resolution.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        algrbraPanel1 = new UI.AlgrbraPanel();
        jPanel3 = new javax.swing.JPanel();
        greekSetsPanel1 = new UI.GreekSetsPanel();
        jPanel4 = new javax.swing.JPanel();
        differentialSetsPanel1 = new UI.DifferentialSetsPanel();
        jPanel5 = new javax.swing.JPanel();
        integralSetsPanel1 = new UI.IntegralSetsPanel();
        jPanel6 = new javax.swing.JPanel();
        setsPanel1 = new UI.SetsPanel();
        jPanel7 = new javax.swing.JPanel();
        quickFormulasPanel1 = new UI.ModesPanel();
        jPanel8 = new javax.swing.JPanel();
        settingsPanel1 = new UI.SettingsPanel();
        jPanel9 = new javax.swing.JPanel();
        introductionPanel1 = new UI.IntroductionPanel();
        functionPanel1 = new UI.FunctionPanel();
        formulaDisplayPanel1 = new UI.FormulaDisplayPanel();
        notification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFormula 0.1.52");

        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        algrbraPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(algrbraPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(algrbraPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Algebra", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(greekSetsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(greekSetsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Greek Sets", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        differentialSetsPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(differentialSetsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 597, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(differentialSetsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Differential Sets", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        integralSetsPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(integralSetsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(integralSetsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Integral Sets", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        setsPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(setsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Sets", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        quickFormulasPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quickFormulasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(quickFormulasPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modes", jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        settingsPanel1.setBorder(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(settingsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Settings", jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(introductionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(introductionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Introduction", jPanel9);

        functionPanel1.setToolTipText("");

        notification.setFont(new java.awt.Font("DejaVuSansMono Nerd Font Mono", 0, 17)); // NOI18N
        notification.setForeground(java.awt.Color.red);
        notification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification.setText("Tips: The x , y in {} are parameters; fun in calculus is the math function; type ^ or _ to render superscript or subscript");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addComponent(functionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(notification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formulaDisplayPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(functionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formulaDisplayPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AboutFrame().setVisible(true);
                    //new MainWindow().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.AlgrbraPanel algrbraPanel1;
    private UI.DifferentialSetsPanel differentialSetsPanel1;
    private UI.FormulaDisplayPanel formulaDisplayPanel1;
    private UI.FunctionPanel functionPanel1;
    private UI.GreekSetsPanel greekSetsPanel1;
    private UI.IntegralSetsPanel integralSetsPanel1;
    private UI.IntroductionPanel introductionPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JLabel notification;
    private UI.ModesPanel quickFormulasPanel1;
    private UI.SetsPanel setsPanel1;
    private UI.SettingsPanel settingsPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dragEnter(DropTargetDragEvent dtde) {
    }

    @Override
    public void dragOver(DropTargetDragEvent dtde) {
        try {
            List<File> files = (List<File>) dtde.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
            if (files.size() != 1) {
                dtde.rejectDrag();
                return;
            }
            if (files.get(0).getName().endsWith(".jft") || files.get(0).getName().endsWith(".txt") || files.get(0).getName().endsWith(".svg")) {
                dtde.acceptDrag(1); // 0 reject 1 Duplicate 2 Move
            } else {
                dtde.rejectDrag();
            }

        } catch (UnsupportedFlavorException ex) {
            return;
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void dropActionChanged(DropTargetDragEvent dtde) {
    }

    @Override
    public void dragExit(DropTargetEvent dte) {
    }

    @Override
    public void drop(DropTargetDropEvent dtde) {
        try {

            dtde.acceptDrop(2);
            String inFileName = "";

            List<File> files = (List<File>) dtde.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
            File inFile = files.get(0);
            inFileName = inFile.getAbsolutePath();

            if (inFileName.endsWith(".jft") || inFileName.endsWith(".txt")) {
                ta_formula.setText(FileUtil.readFile(inFileName));
            } else {

                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            new DisplaySVG(inFile);
                        } catch (Exception ex) {
                            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }, "svgdisplay").start();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(getRootPane(), "Error: " + e.getMessage(), "FATAL ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

}
