/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Util.ConstantsUI;
import SubWindows.SponsorWindow;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import static UI.FormulaDisplayPanel.ta_formula;

/**
 *
 * @author Elliot-VS
 */
public class SettingsPanel extends javax.swing.JPanel implements Runnable {

    public static Color fg;
    public Color bg;

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();

        Thread td = new Thread(this, ConstantsUI.CHANGE_FONT_COLOR_STRING);
        td.start();
        fg = new Color(0, 0, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bt_changefont = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bt_sponsor = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("change the text font and size:");

        bt_changefont.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_changefont.setText("<<<");
        bt_changefont.setActionCommand("...");
        bt_changefont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_changefontActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("ForeColor  & BackColor :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("F...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("B...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bt_sponsor.setFont(new java.awt.Font("KaiTi", 1, 36)); // NOI18N
        bt_sponsor.setText("How to make this software better");
        bt_sponsor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_sponsorMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(bt_changefont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_sponsor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bt_changefont))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(bt_sponsor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JColorChooser colorChooser = new JColorChooser();
                fg = colorChooser.showDialog(null, "Choose a ForeColor", null);
                ta_formula.setForeground(fg);
                jButton1.setForeground(fg);
            }
        });

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JColorChooser colorChooser = new JColorChooser();
        bg = colorChooser.showDialog(null, "Choose a BackColor", Color.WHITE);
        ta_formula.setBackground(bg);
        jButton2.setBackground(bg);

    }//GEN-LAST:event_jButton2ActionPerformed

    boolean isOpen = false;
    private void bt_sponsorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sponsorMouseEntered

        if (!isOpen) {

            JFrame sponsor = new JFrame("Contribute");
            SponsorWindow sw = new SponsorWindow();
            sponsor.setIconImage(ConstantsUI.SPONSOR_ICON);
            sponsor.add(sw);
            sponsor.setResizable(false);
            sponsor.setAlwaysOnTop(true);
            sponsor.pack();
            sponsor.setLocationRelativeTo(null);
            sponsor.setVisible(true);
        }
        
        isOpen = true;
    }//GEN-LAST:event_bt_sponsorMouseEntered

    private void bt_changefontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_changefontActionPerformed
        // TODO add your handling code here:
        FontDialog dialog =FontDialog.getInstance();

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {

                    dialog.setLocationRelativeTo(null);
                    dialog.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

    }//GEN-LAST:event_bt_changefontActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_changefont;
    private javax.swing.JButton bt_sponsor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

        while (true) {
            try {
                Random rd = new Random();

                int r = rd.nextInt(256);
                int g = rd.nextInt(256);
                int b = rd.nextInt(256);
                bt_sponsor.setForeground(new Color(r, g, b));
                Thread.sleep(900);

            } catch (InterruptedException ex) {
                Logger.getLogger(SettingsPanel.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
}
